language: python
python:
  - "3.3"
install:
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - coverage run --include=./test/*.py -m unittest discover -s test
after_success:
  coveralls
