version: 1.0.{build}-{branch}

init:
  - 'C:\Python34\Scripts\pip.exe install py2exe'
  - 'C:\Python34\Scripts\pip.exe install wakeonlan'
install:
  - 'C:\Python34\python.exe setup.py'

build: off

after_build:
  - cmd: 7z a dist\full-app.zip %APPVEYOR_BUILD_FOLDER%\dist\*.*

test_script:
  - 'C:\Python34\python.exe -m unittest discover -s test'

artifacts:
  # pushing all files from the 'dist' dir. This is the dir created by the py2exe setup.py script
  - path: dist\dist\full-app.zip
    name: wol4getmac-with-wrapper

  # pushing all files from the 'dist' dir. This is the dir created by the py2exe setup.py script
  - path: dist\wol4getmac.exe
    name: wol4getmac-exe-only
