version: 1.0.{build}-{branch}

init:
  - 'C:\Python34\Scripts\pip.exe install py2exe'
  - 'C:\Python34\Scripts\pip.exe install wakeonlan'
install:
  - 'C:\Python34\python.exe setup.py'

build: off

test_script:
  - 'C:\Python34\python.exe -m unittest'
